---
title: "nlme_syntax"
author: "Adam Grottoli"
date: "April 20, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nlme)
```


```{r}
RIKZ.lme1 <- lme(Richness ~ NAP, random = ~1 | fBeach, data = RIKZ) #use nlme to run model with beach as a random effect
summary(RIKZ.lme1)
```

```{r}
F0 <- fitted(RIKZ.lme1, level = 0) #level = 0 is the fitted values of the entire population
F1 <- fitted(RIKZ.lme1, level = 1) #level = 1 gives the within-beach fitted values
I <- order(RIKZ$NAP); NAPs <- sort(RIKZ$NAP) #draws the nine lines in the same plot as the population curve
plot(NAPs, F0[I], lwd = 4, type = "l",
ylim = c(0, 22), ylab = "Richness", xlab = "NAP")
for (i in 1:9){
x1 <- RIKZ$NAP[RIKZ$Beach == i]
y1 <- F1[RIKZ$Beach == i]
K <- order(x1)
lines(sort(x1), y1[K])
}
text(RIKZ$NAP, RIKZ$Richness, RIKZ$Beach, cex = 0.9)
```

```{r}
Mlme2 <- lme(Richness ??? NAP, random = ???1 + NAP | fBeach, data = RIKZ)# random slope and intercept
summary(Mlme2)
```

```{r}
F0 <- fitted(Mlme2, level = 0)
F1 <- fitted(Mlme2, level = 1)
I <- order(RIKZ$NAP); NAPs <- sort(RIKZ$NAP)
plot(NAPs, F0[I], lwd = 4, type = "l", ylim = c(0, 22), ylab = "Richness", xlab = "NAP")
for (i in 1:9){
x1 <- RIKZ$NAP[RIKZ$Beach == i]
y1 <- F1[RIKZ$Beach == i]
K <- order(x1)
lines(sort(x1), y1[K])
}
text(RIKZ$NAP, RIKZ$Richness, RIKZ$Beach, cex = 0.9)
```

